# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WeatherUpdateSingapore' do
  pod 'GoogleMaps', '7.3.0'
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WeatherUpdateSingapore

  target 'WeatherUpdateSingaporeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WeatherUpdateSingaporeUITests' do
    # Pods for testing
  end

end
